import type { Metadata } from "next";
import { Roboto,Yuji_Mai,Plus_Jakarta_Sans} from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import Footer from "./components/Footer/footer";

const myfont = Plus_Jakarta_Sans ({
  weight: ["400"]
  })



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={myfont.className} >
         {/* className={`${geistSans.variable} ${geistMono.variable} antialiased`}
       */}
       
      
        
        {children}
      <Footer />
      </body>
    </html>
  );
}
